### ISSUE TITLE
"Insanity Is Doing the Same Thing Over and Over Again ..."

### ISSUE THREAD

**Issue by nelsonic** [dwyl/quotes#27]
This quote might not be "_motivating_" but it certainly is positive change inducing:

![image](https://user-images.githubusercontent.com/194400/83856150-09dd4480-a711-11ea-8533-a1e1e660f34b.png)

Sadly, it _appears_ to be a misattribution:  https://quoteinvestigator.com/2017/03/23/same
https://www.businessinsider.com/misattributed-quotes-2013-10

As much as I _want_ to include it, I cannot find a source for who actually _said_ or _wrote_ it. 😕

**Comment by pscheid92** [comment]
We could add it and use author `unknown` or something similar. The Quote Investigator article could be used as a source.

**Comment by pscheid92** [comment]
Hey @nelsonic, if you wouldn't mind I would open a PR to add the quote 😁

**Comment by nelsonic** [comment]
@pscheid92 go for it. Thanks. 🙌
