### ISSUE TITLE
Hacktoberfest = Quotefest | Proposal for a disclaimer

### ISSUE THREAD

**Issue by iteles** [dwyl/quotes#36]
Given Hacktoberfest is upon us and this is a _super_ easy repo to 'gain some points' on, I suggest we implement a disclaimer at the top of the `readme` that reminds people that all quotes have to be opened as an issue (i.e. _proposed_ as a worthy quote **with a small note on why they are inspired by this quote**) and gets two thumbs up at least before being added as a PR, with the requisite link to the issue and description.

Otherwise, this repo is going to become a bit of a useless free-for-all of standard issue, uninspiring quotes, which is the exact opposite of the stated intention of this repo:

![image](https://user-images.githubusercontent.com/4185328/94816818-3d488b00-03f4-11eb-82ec-90aecff4d3b8.png)

**Comment by nelsonic** [comment]
@iteles yeah, this is a good idea. 👍 
We don't want an arbitrary list of quotes by famous people as noted in the `README.md`:
https://github.com/dwyl/quotes#avoid-quotes-that-dont-inspire-action

But this probably needs to be closer to the _top_ of the Guidelines to avoid a deluge of ["Hacktoberfest" spam](https://blog.domenic.me/hacktoberfest/) ...
https://github.com/dwyl/quotes#guidelines-for-good-quotes

**Comment by iteles** [comment]
:+1: I'm going to write something very direct and explicit at the very top of the repo that we can refer to, but we can always take it down and put up a much smaller reference to the already _great_ contributing section later.

**Comment by iteles** [comment]
Done 👍
