### ISSUE TITLE
Attribution of "... Life is about creating yourself" Quote?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/quotes#62]
The following quote:

## "_Life isn't about finding yourself. Life is about creating yourself._"

Is attributed to [George] Bernard Shaw in the current version of `quotes.json`:

https://github.com/dwyl/quotes/blob/db9678957b7095165f6e7fc29ed4b13424d0517d/quotes.json#L666-L671

https://quoteinvestigator.com/2021/09/28/create-yourself/ suggests it should be  ***Sydney J. Harris***

![image](https://user-images.githubusercontent.com/194400/148795433-9c7cf533-b7b0-4613-8e06-1afc46ddc9db.png)

However the Goodreads page linked to in the **`source`**: https://www.goodreads.com/quotes/8727-life-isn-t-about-finding-yourself-life-is-about-creating-yourself indicates that it's an _accepted_ "fact" ...

![image](https://user-images.githubusercontent.com/194400/148794295-87d4037b-d995-46e5-8aaa-8d5d96da369f.png)

This is George's most "liked" quote ... https://www.goodreads.com/author/quotes/5217.George_Bernard_Shaw

![image](https://user-images.githubusercontent.com/194400/148794665-6255e4f6-7ffb-4c47-98fb-aa6c9b8ce13d.png)

Does it mean that he _said_ (_or wrote it..._) or just that the ***Internet*** has ***liked*** it into being a fact? 🤷‍♂️ 

# What should we do? ignore or fix it?

annoyingly, Sydney J. Harris, does not appear to have this quote on Goodreads:
https://www.goodreads.com/author/quotes/169034.Sydney_J_Harris

![image](https://user-images.githubusercontent.com/194400/148796023-e3c55ea6-3609-4947-b0a2-f9e15e263d51.png)

So I'm inclined to leave it as-is, perhaps with an amendment to the _author_ to include George's first name.

**Comment by dannya** [comment]
> So I'm inclined to leave it as-is, perhaps with an amendment to the author to include George's first name.

This was fixed in `09ce0b885bc70e57dff0192e57084ef619014880`.

**Comment by dannya** [comment]
Is there any further work to do on this issue, or should it be closed?

**Comment by nelsonic** [comment]
Thanks for fixing. Let’s close. 👌

**Comment by dannya** [comment]
@nelsonic great, ready to close when you're ready.
