### ISSUE TITLE
Question: How can I use this for my app?

### ISSUE THREAD

**Issue by Lijukay** [dwyl/quotes#92]
I am relatively new in programming. I never worked with the work of others, that have been licensed. But since you have a lot of quotes, i consider to use them in my app.

There is just one question: As I said, i never worked with licensed works. This was because I am unsure how to give copyright. Now I really want to use it, so I wanted to ask if you might help me a bit.

**Comment by nelsonic** [comment]
Hi @Lijukay how did you discover this repo? 🔍 
The quotes are public domain. There is no copyright on what someone else has said. 💬 
What programming language are using for your `App`? 👩‍💻

**Comment by nelsonic** [comment]
Ok. using `Java` you will want to import the [`quotes.json`](https://github.com/dwyl/quotes/blob/main/quotes.json] file directly and use it however you see fit. 

See: https://stackoverflow.com/questions/10926353/how-to-read-json-file-into-java-with-simple-json-library

**Comment by Lijukay** [comment]
So I just download the JSON file and put it into my apps raw folder and parse it?

**Comment by nelsonic** [comment]
Yes, that will be the easiest/fastest approach. 👌

**Comment by Lijukay** [comment]
Thank you very much for your help 😁

**Comment by nelsonic** [comment]
@Lijukay glad it's helpful. 👌 
Please remember to "star" this repo to help others discover it. ⭐ 
And close the issue once you've made progress on your project. ✅

**Comment by Lijukay** [comment]
Sure, thank you very much 🩵⭐

**Comment by iteles** [comment]
@Lijukay Glad this was helpful, thank you for opening this issue! Please close it if/when your issue is resolved!

**Comment by nelsonic** [comment]
Anyone reading this in the future ... https://github.com/Lijukay/Qwotable 😉
